/**
 * Static demo data used when no API keys are configured (Mock Mode).
 *
 * Purpose:
 *  - History Tab:  shows 3 realistic pre-built feature cards so the dashboard
 *                  never looks empty for portfolio visitors or interviewers.
 *  - Log Analyzer: provides a rich 3-section RCA markdown when no AI key exists.
 *
 * These values are intentionally read-only — they don't touch the database or
 * the file system. The HistoryTab shows them with a subtle "Sample" badge.
 */

import type { FeatureGroup } from "../types";

// ─── Helper ───────────────────────────────────────────────────────────────────

function daysAgo(n: number): string {
  return new Date(Date.now() - n * 86_400_000).toISOString();
}

// ─── Mock Playwright test code snippets ──────────────────────────────────────

export const MOCK_LOGIN_SPEC = `\
// Generated by QA-Genius — UI End-to-End Tests (Mock Mode Demo)
// Feature: User Authentication
// Pattern: Page Object Model + Arrange-Act-Assert

import { test, expect, Page, Locator } from "@playwright/test";

// ─── Page Object ─────────────────────────────────────────────────────────────

class LoginPage {
  readonly emailInput: Locator;
  readonly passwordInput: Locator;
  readonly submitButton: Locator;
  readonly errorAlert: Locator;
  readonly forgotPasswordLink: Locator;

  constructor(readonly page: Page) {
    this.emailInput    = page.getByLabel("Email address");
    this.passwordInput = page.getByLabel("Password");
    this.submitButton  = page.getByRole("button", { name: /sign in|log in/i });
    this.errorAlert    = page.getByRole("alert");
    this.forgotPasswordLink = page.getByRole("link", { name: /forgot.?password/i });
  }

  async navigate() {
    await this.page.goto("/login");
    await this.page.waitForLoadState("networkidle");
  }

  /** Fill credentials and submit the login form. */
  async login(email: string, password: string) {
    await this.emailInput.fill(email);
    await this.passwordInput.fill(password);
    await this.submitButton.click();
  }

  /** Assert the inline validation message contains the expected text. */
  async expectErrorMessage(text: string) {
    await expect(this.errorAlert).toBeVisible();
    await expect(this.errorAlert).toContainText(text);
  }
}

// ─── Test suite ───────────────────────────────────────────────────────────────

test.describe("User Authentication @smoke", () => {
  let loginPage: LoginPage;

  test.beforeEach(async ({ page }) => {
    loginPage = new LoginPage(page);
    await loginPage.navigate();
  });

  test("TC-001: should redirect to dashboard after valid login", async ({ page }) => {
    // Arrange
    const credentials = { email: "user@example.com", password: "ValidPass1!" };

    // Act
    await loginPage.login(credentials.email, credentials.password);

    // Assert
    await expect(page).toHaveURL(/\\/dashboard/);
    await expect(page.getByRole("heading", { name: /welcome/i })).toBeVisible();
  });

  test("TC-002: should show error for invalid password @regression", async () => {
    // Arrange — valid email, wrong password
    // Act
    await loginPage.login("user@example.com", "wrong-password");

    // Assert
    await loginPage.expectErrorMessage("Invalid email or password");
  });

  test("TC-003: should show validation error when email is empty", async () => {
    // Arrange — intentionally leave email blank
    // Act
    await loginPage.login("", "somepassword");

    // Assert
    await loginPage.expectErrorMessage("Email is required");
  });

  test("TC-004: should display forgot-password link @smoke", async () => {
    // Assert
    await expect(loginPage.forgotPasswordLink).toBeVisible();
    await expect(loginPage.forgotPasswordLink).toHaveAttribute("href", /\\/forgot-password/);
  });
});
`;

export const MOCK_PAYMENT_SPEC = `\
// Generated by QA-Genius — UI End-to-End Tests (Mock Mode Demo)
// Feature: Payment Gateway Checkout
// Pattern: Page Object Model + Arrange-Act-Assert + Network Mocking

import { test, expect, Page, Locator } from "@playwright/test";

// ─── Page Object ─────────────────────────────────────────────────────────────

class CheckoutPage {
  readonly cardNumberInput: Locator;
  readonly expiryInput: Locator;
  readonly cvvInput: Locator;
  readonly payButton: Locator;
  readonly successBanner: Locator;
  readonly errorBanner: Locator;
  readonly orderSummary: Locator;

  constructor(readonly page: Page) {
    this.cardNumberInput = page.getByLabel("Card number");
    this.expiryInput     = page.getByLabel("Expiry date");
    this.cvvInput        = page.getByLabel("CVV");
    this.payButton       = page.getByRole("button", { name: /pay now|complete order/i });
    this.successBanner   = page.getByTestId("payment-success");
    this.errorBanner     = page.getByRole("alert");
    this.orderSummary    = page.getByTestId("order-summary");
  }

  async navigate() {
    await this.page.goto("/checkout");
    await this.page.waitForLoadState("networkidle");
  }

  async fillCard(number: string, expiry: string, cvv: string) {
    await this.cardNumberInput.fill(number);
    await this.expiryInput.fill(expiry);
    await this.cvvInput.fill(cvv);
  }
}

// ─── Test suite ───────────────────────────────────────────────────────────────

test.describe("Payment Gateway Checkout @critical", () => {
  let checkout: CheckoutPage;

  test.beforeEach(async ({ page }) => {
    checkout = new CheckoutPage(page);
    // Seed cart via API before each test
    await page.request.post("/api/cart/seed", { data: { productId: "prod_001", qty: 2 } });
    await checkout.navigate();
  });

  test("TC-001: should complete a successful payment with valid card", async ({ page }) => {
    // Arrange — intercept Stripe API to avoid real charges
    await page.route("**/api/payment/**", (route) =>
      route.fulfill({ status: 200, body: JSON.stringify({ status: "succeeded", chargeId: "ch_mock_001" }) })
    );

    // Act
    await checkout.fillCard("4242 4242 4242 4242", "12/27", "123");
    await checkout.payButton.click();

    // Assert
    await expect(checkout.successBanner).toBeVisible({ timeout: 10_000 });
    await expect(checkout.successBanner).toContainText("Payment confirmed");
  });

  test("TC-002: should show error when card is declined @regression", async ({ page }) => {
    // Arrange — simulate a declined card response
    await page.route("**/api/payment/**", (route) =>
      route.fulfill({ status: 402, body: JSON.stringify({ error: "card_declined" }) })
    );

    // Act
    await checkout.fillCard("4000 0000 0000 0002", "12/27", "123");
    await checkout.payButton.click();

    // Assert
    await checkout.errorBanner.waitFor({ state: "visible" });
    await expect(checkout.errorBanner).toContainText("declined");
  });

  test("TC-003: order summary should reflect cart contents", async () => {
    // Assert — order summary shows the pre-seeded product
    await expect(checkout.orderSummary).toContainText("prod_001");
    await expect(checkout.orderSummary).toContainText("×2");
  });
});
`;

export const MOCK_API_SPEC = `\
// Generated by QA-Genius — API Integration Tests (Mock Mode Demo)
// Feature: Users REST API
// Source: OpenAPI 3.0 specification

import { test, expect } from "@playwright/test";

const BASE_URL = process.env.BASE_URL ?? "http://localhost:3000";

test.describe("Users API — Integration Tests @api", () => {
  let authToken: string;

  test.beforeAll(async ({ request }) => {
    // Authenticate and store JWT for subsequent tests
    const res = await request.post(\`\${BASE_URL}/auth/login\`, {
      data: { email: "test@example.com", password: process.env.TEST_PASSWORD ?? "testpassword" },
    });
    if (res.ok()) {
      const body = await res.json();
      authToken = body.access_token ?? body.token ?? "mock-token";
    }
  });

  test("TC-001: GET /users — should return paginated list @smoke", async ({ request }) => {
    // Arrange + Act
    const res = await request.get(\`\${BASE_URL}/users\`, {
      headers: { Authorization: \`Bearer \${authToken}\` },
    });

    // Assert
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(body.data).toBeDefined();
    expect(Array.isArray(body.data)).toBeTruthy();
    expect(body.pagination).toHaveProperty("total");
  });

  test("TC-002: POST /users — should create a new user", async ({ request }) => {
    // Arrange
    const payload = { name: "QA Tester", email: \`qa_\${Date.now()}@test.com\`, role: "viewer" };

    // Act
    const res = await request.post(\`\${BASE_URL}/users\`, {
      headers: { Authorization: \`Bearer \${authToken}\`, "Content-Type": "application/json" },
      data: payload,
    });

    // Assert
    expect(res.status()).toBe(201);
    const body = await res.json();
    expect(body.id).toBeDefined();
    expect(body.email).toBe(payload.email);
  });

  test("TC-003: GET /users — should return 401 without token", async ({ request }) => {
    const res = await request.get(\`\${BASE_URL}/users\`);
    expect(res.status()).toBe(401);
  });
});
`;

// ─── Mock Feature History ─────────────────────────────────────────────────────

export const MOCK_FEATURES: FeatureGroup[] = [
  {
    meta: {
      featureName: "User Authentication",
      slug: "user_authentication",
      inputType: "prd",
      createdAt: daysAgo(4),
      updatedAt: daysAgo(2),
      description: "Login flow · Password reset · Session management · OAuth",
    },
    tests: [
      {
        fileName: "login.spec.ts",
        featureName: "User Authentication",
        featureSlug: "user_authentication",
        relativePath: "user_authentication/login.spec.ts",
        sizeBytes: MOCK_LOGIN_SPEC.length,
        createdAt: daysAgo(4),
        modifiedAt: daysAgo(2),
        preview: "import { test, expect, Page, Locator } from '@playwright/test'; // LoginPage POM",
      },
    ],
  },
  {
    meta: {
      featureName: "Payment Gateway",
      slug: "payment_gateway",
      inputType: "prd",
      createdAt: daysAgo(7),
      updatedAt: daysAgo(5),
      description: "Stripe checkout · Card validation · 3DS · Decline handling",
    },
    tests: [
      {
        fileName: "checkout.spec.ts",
        featureName: "Payment Gateway",
        featureSlug: "payment_gateway",
        relativePath: "payment_gateway/checkout.spec.ts",
        sizeBytes: MOCK_PAYMENT_SPEC.length,
        createdAt: daysAgo(7),
        modifiedAt: daysAgo(5),
        preview: "import { test, expect, Page, Locator } from '@playwright/test'; // CheckoutPage POM",
      },
    ],
  },
  {
    meta: {
      featureName: "Users REST API",
      slug: "users_rest_api",
      inputType: "swagger",
      createdAt: daysAgo(10),
      updatedAt: daysAgo(9),
      description: "GET /users · POST /users · PATCH /users/:id — OpenAPI 3.0 spec",
    },
    tests: [
      {
        fileName: "users_api.spec.ts",
        featureName: "Users REST API",
        featureSlug: "users_rest_api",
        relativePath: "users_rest_api/users_api.spec.ts",
        sizeBytes: MOCK_API_SPEC.length,
        createdAt: daysAgo(10),
        modifiedAt: daysAgo(9),
        preview: "import { test, expect } from '@playwright/test'; // API Integration Tests",
      },
    ],
  },
];

// ─── Mock code map for the "View Code" modal in the History tab ───────────────

export const MOCK_CODE_MAP: Record<string, string> = {
  "user_authentication/login.spec.ts": MOCK_LOGIN_SPEC,
  "payment_gateway/checkout.spec.ts": MOCK_PAYMENT_SPEC,
  "users_rest_api/users_api.spec.ts": MOCK_API_SPEC,
};

// ─── Mock Log Analysis (used by Log Analyzer in Mock Mode) ───────────────────

export const MOCK_LOG_ANALYSIS_MARKDOWN = `\
## 🚨 Root Cause

A **database connection pool exhaustion** in the \`checkout-service\` caused all payment API requests to queue indefinitely, resulting in HTTP 500 responses to users and a cascading Playwright test failure on the order confirmation page.

---

## 🔍 Technical Breakdown

**Component:** \`checkout-service\` → \`PaymentController.processPayment()\`

**Primary error (first event):**
\`\`\`
[2024-01-15T14:23:01Z] [ERROR] checkout-service: TimeoutError: Connection pool exhausted — waited 5000ms for a free connection (pool.max=10, pool.active=10, pool.idle=0)
  at PgPool.acquire (/app/node_modules/pg-pool/index.js:122)
  at PaymentRepository.createTransaction (/app/src/payment/payment.repository.ts:67)
\`\`\`

**Propagation chain:**
1. A long-running DB migration started at 14:18 UTC, holding 8 of 10 pool connections open.
2. A traffic spike at 14:22 UTC (Black Friday load test) consumed the remaining 2 connections.
3. New incoming checkout requests waited 5 s for a free connection, then threw \`TimeoutError\`.
4. Express global error handler was missing — \`TimeoutError\` propagated as an unhandled rejection, crashing the process (exit code 1).
5. PM2 restarted the service, but the migration was still holding connections → crash loop.
6. The Playwright E2E test timed out waiting for \`page.getByTestId("payment-success")\` to appear (assertion budget: 10 s).

**Severity:** 🔴 Critical — production payment processing was unavailable for ~11 minutes.

---

## 💡 Actionable Fix

1. **Dev — Increase connection pool ceiling:** In \`src/config/database.ts\`, raise \`pool.max\` from 10 → 25 for the \`checkout-service\`. Add \`pool.acquireTimeoutMillis: 3000\` so requests fail fast instead of stacking.

2. **Dev — Wrap async handlers:** Install \`express-async-errors\` and wrap every route:
   \`\`\`ts
   import 'express-async-errors';
   // All thrown errors in async routes are now caught by the global handler
   \`\`\`

3. **Dev — Run migrations in a separate process:** Use a dedicated migration runner (e.g., \`db-migrate\`) that operates on a separate connection outside the app pool. Never run long migrations through the app server connection pool.

4. **QA — Add a circuit-breaker test:** Use \`page.route()\` to simulate pool exhaustion:
   \`\`\`ts
   await page.route('**/api/payment/**', route =>
     route.fulfill({ status: 503, body: JSON.stringify({ error: 'service_unavailable' }) })
   );
   // Assert: error banner is shown, retry button is visible
   \`\`\`

5. **Dev — Set up Coralogix alert:** Create a rule that fires when \`pool.idle = 0\` for > 30 s, notifying the on-call engineer before the pool fully saturates.

6. **QA — Add load test to CI pipeline:** Integrate \`k6\` to run 50 concurrent checkout users in a staging environment before every production deployment to catch pool limits early.
`;
